spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: stocksba-stock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://9.112.134.36:31003/sba_stock?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: sba_stock
    password: sba_stock_666
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
file:
  upload-dir: /Users/yuanbing/upload-dir/
server:
  servlet:
    context-path: /stock
  port: 9995

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000
        


logging:
 level: 
  com:
   sba:
    course:
     mapper: Debug  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    
# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true
  
---
spring:
  profiles: k8s
  application:
    name: stocksba-stock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stocksba-stock-db:3306/sba_stock?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: sba_stock
    password: sba_stock_666
    
file:
  upload-dir: /upload-dir/
server:
  servlet:
    context-path: /stock
  port: 9995
  
eureka:
  client:
    service-url:
      defaultZone: http://stocksba-registry:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
#        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

swagger.enabled: true

feign:
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000 
